name: interactive-sentinel-2-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab
  - pandas
  - xarray
  - dask
  - hvplot
  - geoviews
  - panel
  - bokeh
  - jupyter_bokeh
  - planetary-computer
  - pystac-client
  - odc-stac
  - pip:
      - sphinx-pythia-theme
